---

- name: Install EPEL
  yum: name=epel-release state=present

- name: Update to latest packages
  yum: "name='*' state=latest"

- name: Install yum-cron
  yum: name=yum-cron state=latest

- name: Copy yum-cron config
  copy: src=yum-cron.conf dest=/etc/yum/yum-cron.conf
