version: 2.1

# Required in CircleCI: DOCKERHUB_USER, DOCKERHUB_PASS

commands:
  build_image:
    parameters:
      step_name:
        type: string
      image_name:
        type: string
      organization:
        type: string
    steps:
      - run:
          name: << parameters.step_name >>
          command: |
            export LATEST_COMMIT_HASH=`git rev-list -1 HEAD`
            export FOLDER_COMMIT_HASH=`git rev-list -1 HEAD << parameters.image_name >>`
            echo "LATEST_COMMIT_HASH=$LATEST_COMMIT_HASH"
            echo "FOLDER_COMMIT_HASH=$FOLDER_COMMIT_HASH"

            if [[ $LATEST_COMMIT_HASH == $FOLDER_COMMIT_HASH ]]; then
              cd << parameters.image_name >>
              docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
              docker build -t << parameters.organization >>/<< parameters.image_name >> .
              docker push << parameters.organization >>/<< parameters.image_name >>
            fi

  build_all:
    steps:
      - run:
          name: build_all
          command: |
            for image in `ls | grep -v README.md`
            do
              echo "Processing $image"
              export LATEST_COMMIT_HASH=`git rev-list -1 HEAD`
              export FOLDER_COMMIT_HASH=`git rev-list -1 HEAD "$image"`
              echo "LATEST_COMMIT_HASH=$LATEST_COMMIT_HASH"
              echo "FOLDER_COMMIT_HASH=$FOLDER_COMMIT_HASH"

              if [[ $LATEST_COMMIT_HASH == $FOLDER_COMMIT_HASH ]]; then
                echo "Building..."
                cd "$image"
                docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
                docker build -t "interchainio/$image" .
                docker push "interchainio/$image"
             fi

jobs:
  build:
    machine: true
    steps:
      - checkout
#      - build_image:
#          step_name: "Build terragrunt"
#          image_name: "terragrunt"
#          organization: "interchainio"
      - build_all:

workflows:
  version: 2.1
  images:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
