version: 2.1

# Required in CircleCI: DOCKERHUB_USER, DOCKERHUB_PASS, AWS credentials in context

executors:
  ami_packer:
    docker:
      - image: interchainio/packer
    environment:
      AWS_REGION: us-east-1

commands:
  build_docker:
    steps:
      - run:
          name: "Build all Docker images"
          command: |
            for image in `find . -maxdepth 1 -type d -name '[^.]*' | sed 's,./,,'`
            do
              test -f "${image}/Dockerfile" || continue
              echo "Processing ${image}"
              export LATEST_COMMIT_HASH=`git rev-list -1 HEAD`
              export FOLDER_COMMIT_HASH=`git rev-list -1 HEAD "${image}"`
              echo "LATEST_COMMIT_HASH=$LATEST_COMMIT_HASH"
              echo "FOLDER_COMMIT_HASH=$FOLDER_COMMIT_HASH"

              #Trigger all builds temporarily
              export LATEST_COMMIT_HASH=$FOLDER_COMMIT_HASH

              if [[ $LATEST_COMMIT_HASH == $FOLDER_COMMIT_HASH ]]; then
                echo "Building..."
                cd "${image}"
                docker login -u "${DOCKERHUB_USER}" --password-stdin <<< "${DOCKERHUB_PASS}"
                docker build -t "interchainio/${image}" .
                docker push "interchainio/${image}"
              fi
            done

  build_ami:
    steps:
      - run:
          name: "Build all AMI images"
          command: |
            for image in `find . -maxdepth 1 -type d -name '[^.]*' | sed 's,./,,'`
            do
              test -f "${image}/packer.json" || continue
              echo "Processing ${image}"
              export LATEST_COMMIT_HASH=`git rev-list -1 HEAD`
              export FOLDER_COMMIT_HASH=`git rev-list -1 HEAD "${image}"`
              echo "LATEST_COMMIT_HASH=$LATEST_COMMIT_HASH"
              echo "FOLDER_COMMIT_HASH=$FOLDER_COMMIT_HASH"

              #Trigger all builds temporarily
              export LATEST_COMMIT_HASH=$FOLDER_COMMIT_HASH

              if [[ $LATEST_COMMIT_HASH == $FOLDER_COMMIT_HASH ]]; then
                echo "Building..."
                cd "${image}"
                packer build packer.json
              fi
            done

jobs:
  build_docker:
    machine: true
    steps:
      - checkout
      - build_docker
  build_ami:
    executor: ami_packer
    steps:
      - checkout
      - build_ami

workflows:
  docker_deployment:
    jobs:
      - build_docker:
          filters:
            branches:
              only:
                - master
  ami_deployment:
    jobs:
      - build_ami:
          context: dev_imagepacker
          filters:
            branches:
              only:
                - master
      - build_ami:
          context: prod_imagepacker
          filters:
            branches:
              only:
                - master
