version: 2.1

# Required in CircleCI: DOCKERHUB_USER, DOCKERHUB_PASS, AWS credentials in context

executors:
  ami_packer:
    docker:
      - image: interchainio/packer
    environment:
      AWS_REGION: us-east-1

commands:
  build_docker:
    steps:
      - run:
          name: "Build all Docker images"
          command: |
            docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
            for image in `find . -maxdepth 1 -type d -name '[^.]*' | sed 's,./,,'`
            do
              test -f "${image}/Dockerfile" || continue
              echo "Processing ${image}"
              export LATEST_COMMIT_HASH=`git rev-list -1 HEAD`
              export FOLDER_COMMIT_HASH=`git rev-list -1 HEAD "${image}"`
              echo "LATEST_COMMIT_HASH=$LATEST_COMMIT_HASH"
              echo "FOLDER_COMMIT_HASH=$FOLDER_COMMIT_HASH"

              if [[ $LATEST_COMMIT_HASH == $FOLDER_COMMIT_HASH ]]; then
                echo "Building..."
                docker build -t "interchainio/${image}" "${image}"
                docker push "interchainio/${image}"
              fi
            done
            docker logout

  build_ami:
    parameters:
      product_name:
        type: string
    steps:
      - run:
          name: "Build all AMI images"
          command: |
            export AWS_ROLE="$(aws ssm get-parameters --output text --name /<< parameters.product_name >>/role_arn --region ${AWS_REGION} --query 'Parameters[0].Value')"
            export AWS_STS=($(aws sts assume-role --output text --role-arn ${AWS_ROLE} --role-session-name packer-ami-build --duration-seconds 900 --query '[Credentials.AccessKeyId,Credentials.SecretAccessKey,Credentials.SessionToken,Credentials.Expiration]'))
            export AWS_ACCESS_KEY_ID="${AWS_STS[0]}"
            export AWS_SECRET_ACCESS_KEY="${AWS_STS[1]}"
            export AWS_SESSION_TOKEN="${AWS_STS[2]}"
            export PYTHONWARNINGS="ignore"
            for image in `find . -maxdepth 1 -type d -name '[^.]*' | sed 's,./,,'`
            do
              test -f "${image}/packer.json" || continue
              echo "Processing ${image}"
              export LATEST_COMMIT_HASH=`git rev-list -1 HEAD`
              export FOLDER_COMMIT_HASH=`git rev-list -1 HEAD "${image}"`
              echo "LATEST_COMMIT_HASH=$LATEST_COMMIT_HASH"
              echo "FOLDER_COMMIT_HASH=$FOLDER_COMMIT_HASH"

              if [[ $LATEST_COMMIT_HASH == $FOLDER_COMMIT_HASH ]]; then
                echo "Building..."
                cd "${image}"
                packer build packer.json
                cd ..
              fi
            done

jobs:
  build_docker:
    machine: true
    steps:
      - checkout
      - build_docker
  build_ami:
    executor: ami_packer
    parameters:
      product_name:
        type: string
    steps:
      - checkout
      - build_ami:
          product_name: << parameters.product_name >>

workflows:
  deploy:
    jobs:
      - build_docker:
          filters:
            branches:
              only:
                - master
      - build_ami:
          product_name: dev_imagepacker
          context: dev_imagepacker
          requires:
            - build_docker
          filters:
            branches:
              only:
                - master
      - build_ami:
          product_name: prod_imagepacker
          context: prod_imagepacker
          requires:
            - build_docker
          filters:
            branches:
              only:
                - master
