proxy_app = "kvstore"
moniker = "dockernode"
[rpc]
laddr = "tcp://0.0.0.0:26657"
unsafe = true
[p2p]
addr_book_strict = false
handshake_timeout = "5s"
[consensus]
timeout_propose = "1s"
timeout_propose_delta = "200ms"
timeout_prevote = "1s"
timeout_prevote_delta = "200ms"
timeout_precommit = "1s"
timeout_precommit_delta = "200ms"
timeout_commit = "1s"
skip_timeout_commit = true
[tx_index]
index_all_tags = true
[instrumentation]
prometheus = true

