---
#From: https://github.com/signalfx/signalfx-agent/blob/master/deployments/ansible/roles/signalfx-agent/defaults/main.yml
# Default values for for Signalfx Agent installation

sfx_repo_base_url: https://dl.signalfx.com
sfx_package_stage: final
sfx_version: latest

sfx_conf_file_path: /etc/signalfx/agent.yaml

sfx_agent_config:
  signalFxAccessToken: "{{ lookup('env', 'SFX_TOKEN') }}"
  signalFxRealm: us1
  enableBuiltInFiltering: true
  monitors:
    - type: collectd/cpu
    - type: collectd/cpufreq
    - type: collectd/df
    - type: collectd/disk
    - type: collectd/interface
    - type: collectd/load
    - type: collectd/memory
    - type: collectd/signalfx-metadata
    - type: host-metadata
    - type: collectd/vmem
