---

- name: Download InfluxDB
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.6.x86_64.rpm
    checksum: sha256:ffcf0def4a0bffb74728c7aaa0ade39231ea4e91b3be67de5528d7982b295ea8
    dest: /tmp/influxdb.rpm

- name: Install InfluxDB
  yum: name=/tmp/influxdb.rpm lock_timeout=180


- name: Download Grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana-6.1.6-1.x86_64.rpm
    checksum: sha256:125cea2958d9fe8db69c96f92bb0f7cb1ace1e5b09023f69608d86160d165c3e
    dest: /tmp/grafana.rpm

- name: Install Grafana
  yum: name=/tmp/grafana.rpm lock_timeout=180

# keep the / at the end of dest so the folder is created
- name: Copy permission override for grafana for privileged ports
  copy: src=override.conf dest=/etc/systemd/system/grafana-server.service.d/
  notify: daemon reload

- name: Remove install packages
  file: "path={{item}} state=absent"
  with_items:
    - /tmp/influxdb.rpm
    - /tmp/grafana.rpm

- name: Install nginx on Amazon Linux
  command: "amazon-linux-extras install -y nginx1.12"
  args:
    creates: /usr/lib/systemd/system/nginx.service

- name: Configure nginx for Grafana upstream
  copy: src=nginx-grafana.conf dest=/root/nginx-grafana.conf
  notify:
    - enable nginx
